stages:
  - test
  - build
  - security

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: "api-devsecops:$CI_COMMIT_SHORT_SHA"

# 🛡️ TASK 1: Scanner de Credenciais e Segredos Vazados
gitleaks-scan:
  stage: test
  image: 
    name: zricethezav/gitleaks:latest
    entrypoint: [""]
  script:
    - gitleaks detect --verbose --source=.
  allow_failure: true

# 🔍 TASK 2: Análise Estática de Código (SAST)
semgrep-sast:
  stage: test
  image: semgrep/semgrep:latest
  variables:
    SEMGREP_IN_DOCKER: "0"
  script:
    - semgrep ci --config auto
  allow_failure: true

# 🧱 TASK 3: Scanner de Infraestrutura como Código (IaC - Terraform)
checkov-scan:
  stage: test
  image:
    name: bridgecrew/checkov:latest
    entrypoint: [""]
  script:
    - checkov -d infra/
  allow_failure: true
