stages:
  - test
  - build
  - security

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  # Define o nome e a tag dinâmica da imagem para o pipeline
  IMAGE_NAME: "api-devsecops:$CI_COMMIT_SHORT_SHA"

# 🛡️ TASK 1: Scanner de Infraestrutura (IaC) com Checkov
checkov-scan:
  stage: test
  image: 
    name: bridgecrew/checkov:latest
    entrypoint: [""]
  script:
    - checkov -d infra/
  allow_failure: false # Trava a esteira se a infra estiver insegura

# 🐳 TASK 2: Build do Container da API
docker-build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    # Builda a imagem localmente no runner
    - docker build -t $IMAGE_NAME .
    # Exporta a imagem para um arquivo compactado para o próximo estágio ler
    - docker save -o image.tar $IMAGE_NAME
  artifacts:
    paths:
      - image.tar
    expire_in: 1 hour # O artefato expira rápido para não lotar o storage do GitLab

# 🔍 TASK 3: Container Scanning & SCA com AquaSec Trivy
trivy-scan:
  stage: security
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  services:
    - docker:24.0.5-dind
  script:
    # Carrega a imagem gerada no estágio anterior para dentro do ambiente do Trivy
    - docker load -i image.tar
    # Escaneia procurando falhas ALTAS e CRÍTICAS. Se achar alguma CRITICAL, quebra o pipeline (--exit-code 1)
    - trivy image --severity HIGH,CRITICAL --exit-code 1 $IMAGE_NAME
  allow_failure: false
