stages:
  - test
  - build
  - security

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: "api-devsecops:$CI_COMMIT_SHORT_SHA"

# --- ESTÁGIO DE TESTES ---
gitleaks-scan:
  stage: test
  image: 
    name: zricethezav/gitleaks:latest
    entrypoint: [""]
  script:
    - gitleaks detect --verbose --source=.
  allow_failure: true

semgrep-sast:
  stage: test
  image: semgrep/semgrep:latest
  variables:
    SEMGREP_IN_DOCKER: "0"
  script:
    - semgrep ci --config auto
  allow_failure: true

checkov-scan:
  stage: test
  image:
    name: bridgecrew/checkov:latest
    entrypoint: [""]
  script:
    - checkov -d infra/
  allow_failure: true

# --- ESTÁGIO DE BUILD ---
docker-build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - docker build -t $IMAGE_NAME .
    # Salva a imagem em um arquivo para o próximo estágio conseguir ler
    - docker save -o image.tar $IMAGE_NAME
  artifacts:
    paths:
      - image.tar
    expire_in: 1 hour

# --- ESTÁGIO DE SEGURANÇA DE CONTAINER ---
trivy-scan:
  stage: security
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    # Carrega a imagem gerada no estágio anterior
    - trivy image --input image.tar --severity HIGH,CRITICAL --exit-code 0
  allow_failure: true
